version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_file_version: '%APPVEYOR_BUILD_VERSION%'
  assembly_informational_version: '%APPVEYOR_BUILD_VERSION%'
before_build:
  - cmd: cd src 
  - cmd: nuget restore
build:
  project: src/NEventStore.NServiceBus.sln
  verbosity: normal
before_test:
  - cmd: sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE Dispatcher" -d "master"
  - ps: $EndpointProcess = Start-Process C:\projects\neventstore-nservicebus\src\Tests.Acceptance.Endpoint\bin\Release\Tests.Acceptance.Endpoint.exe -PassThru 
test:
  assemblies:
  - 'Tests.Unit.dll'
  - 'Tests.Acceptance.dll'
services:
  - mssql2014
  - msmq
on_finish:
  - ps: Stop-Process -Id $EndpointProcess.Id